### ISSUE TITLE
is There any example for usage!

### ISSUE THREAD

**Issue by ghost** [jlmadurga/listenclosely-whatsapp#1]
Hi;

Is there any simple example to use it ?
I know some bit about YowSup but I don't understand listenclosely-whatsapp.

After I register via YowSup what should I do ? how can I use listenclosely-whatsapp ? is there any example to send msg via listenclosely-whatsapp ?

thanks.

**Comment by jlmadurga** [comment]
listen-closely whatsapp is a backend for https://github.com/jlmadurga/listenclosely that can be used also with telegram
